#!/bin/bash
# linux-pos.sh - o script que atualiza o computador baseado em linux.
# Este script faz parte do https://github.com/RobersonMint20/linux-pos
#
#
# Loop que mostra o menu principal
while : ; do

    # Mostra o menu na tela, com as ações disponíveis
    resposta=$(
      dialog --stdout               \
             --title 'Automação'  \
             --menu 'Escolha o quê você quer fazer:' \
            0 0 0                     \
            1  'Youtube DLG'          \
        2  'Slimjet'                  \
        3  'chromium-browser'         \
        4  'VLC player'               \
        5  'kdenlive'                 \
        6  'gimp'                     \
        7  'gparted'                  \
        8  'wine'                     \
        9  'simplescreenrecorder'     \
        11  'libreoffice'             \
        12  'vivaldi'                 \
        13  'unetbootin'              \
        14  'libreoffice'             \
        15  'liferea'                 \
        16  'curlew'                  \
        17  'Opera'                   \
        18  'Codec'                   \
        19  'Lollypop'                \
        20  'Veracryter'              \
        21  'Atom'              \
            0 'Sair'                )

    # Ela apertou CANCELAR ou ESC, então vamos sair...
    [ $? -ne 0 ] && break

    # De acordo com a opção escolhida, dispara programas
    case "$resposta" in
         1) sudo add-apt-repository ppa:nilarimogard/webupd8
        sudo apt-get update
        sudo apt-get install youtube-dlg -y;;

         2) wget -q https://www.slimjet.com/pt/postdl.php?version=lnx32&type=deb -O- | sudo apt-key add -
        sudo apt-get update
        sudo apt-get install slimjet -y;;

         3) sudo add-apt-repository ppa:chromium/stable-daily
        sudo apt-get update
        sudo apt-get install chromium-browser -y;;

         4)  sudo apt-get install vlc -y;;

         5) sudo add-apt-repository ppa:kdenlive/stable-daily
        sudo apt-get update
        sudo apt-get install kdenlive -y;;

         6) sudo add-apt-repository ppa:gimp/stable-daily
        sudo apt-get update
        sudo apt-get install gimp -y;;

         7) sudo add-apt-repository ppa:gparted/stable-daily
        sudo apt-get update
        sudo apt-get install gparted -y;;

         8) sudo add-apt-repository ppa:wine/stable-daily
        sudo apt-get  aupdate
        sudo apt-get install wine -y;;

         9) sudo add-apt-repository ppa:simplescreenrecorder/stable-daily
        sudo apt-get update
        sudo apt-get install simplescreenrecorder -y;;

         10) sudo add-apt-repository ppa:libreoffice/stable-daily
        sudo apt-get update
        sudo apt-get install libreoffice -y;;

         11) sudo add-apt-repository ppa:rar/stable-daily
        sudo apt-get update
        sudo apt-get install rar -y;;

         12) wget -qO- https://repo.vivaldi.com/archive/linux_signing_key.pub | sudo apt-key add -
         sudo add-apt-repository 'deb https://repo.vivaldi.com/archive/deb/ stable main'
         sudo apt update
         sudo apt install vivaldi-stable;;

         13) sudo add-apt-repository ppa:gezakovacs/ppa
        sudo apt-get update
        sudo apt-get install unetbootin -y;;

         14) sudo add-apt-repository ppa:libreoffice/ppa
        sudo apt-get update
        sudo apt install libreoffice -y;;

         15) sudo add-apt-repository ppa:klaus-vormweg/ppa
        sudo apt-get update
        sudo apt-get install liferea -y;;

         16) sudo add-apt-repository ppa:upubuntu-com/multimedia
        sudo apt-get update
        sudo apt-get install curlew -y;;

         17) sudo wget http://deb.opera.com/opera/pool/non-free/o/opera-stable/opera-stable_45.0.2552.898_i386.deb -O opera.deb
        sudo dpkg -i opera.deb
        sudo apt-get install -f;;

         18) sudo ffmpeg -version;
        sudo apt-get install -y software-properties-common
        add apt-repository ppa:mc3man/trusty-media;;

         19) sudo add-apt-repository ppa:gnumdk/lollypop
        sudo apt-get update
        sudo apt-get install lollypop;;

         20) sudo wget "https://launchpad.net/veracrypt/trunk/1.24-update4/+download/veracrypt-1.24-Update4-setup.tar.bz2" -O veracrypt.tar.bz2
        sudo tar -xjvf veracrypt.tar.bz2
        sudo ./veracrypt-1.24-Update4-setup-console-x86
        sudo rm veracrypt*;;

         21)sudo add-apt-repository ppa:webupd8team/atom
         sudo apt-get update
         sudo apt-get install atom;;

         0) break ;;
    esac

done

# Mensagem final :)
echo 'Tchau!'
